# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - projobj

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_992c9742b3e74de48256c8b1d2237d14 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6f195288fb3545119d4121c6373e89e0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_992c9742b3e74de48256c8b1d2237d14 }}/projobj8:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projobj'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_806e03e689694341a4d6ac9f60ad6a9f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_992c9742b3e74de48256c8b1d2237d14 }}/projobj8:${{ github.sha }}'