# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - projobj2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1ee734aea6974d76b586bd303a7bfb8e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa25d5c0d58e49bbb73cb41c8cf5dae0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1ee734aea6974d76b586bd303a7bfb8e }}/projobj5:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'projobj2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c7f95e251e464511a4517a18a372f885 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1ee734aea6974d76b586bd303a7bfb8e }}/projobj5:${{ github.sha }}'